version: "3.8"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TRUST_DOWNSTREAM_PROXY=false
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d:rw
      - ./html:/usr/share/nginx/html:rw

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-letsencrypt
    depends_on:
      - nginx-proxy
    restart: always
    environment:
      - DEFAULT_EMAIL=youremail@example.com         # CHANGE THIS for your email
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d:rw
      - ./html:/usr/share/nginx/html:rw

  app:
    build: .
    env_file:
      - .env
    restart: always
    environment:
      - VIRTUAL_HOST=chatpsych-playground.org       # CHANGE THIS for your domain
      - LETSENCRYPT_HOST=chatpsych-playground.org   # CHANGE THIS for your domain
      - LETSENCRYPT_EMAIL=youremail@example.com     # CHANGE THIS for your email
    expose:
      - "8000"
    volumes:
      - /srv/chatpsych/data:/app/data:rw
      
# optional: use named volume for internal docker-only data (commented out here since you use host mount)
# volumes:
#   data: